### PR TITLE
chapter: unaligned-models

### PR DESCRIPTION
**Pull request by casperdcl**
## Review checklist

> Don't worry about satisfying all items, it's fine to open a (draft) PR.

- [x] chapter content
  + [x] only one top-level `# h1-Title`
  + [x] summary (e.g. table or TL;DR overview), no need for an explicit `## Summary/Introduction` title or equivalent
  + [x] main content focus: recent developments in open source AI
    + general context/background (brief)
    + current pros/cons
    + in-depth insights (not yet widely known)
  + [x] likely `## Future` developments
  + [x] end with `{{ comments }}`
- [x] appropriate citations
  + [x] BibTeX references
  + [x] Glossary terms
  + [x] cross-references (figures/chapters)
  + [x] (if `new-chapter.md`), add `_toc.yml` entry & `index.md` table row
  + [x] If CI URL checks have false-positives, append to `_config.yml:sphinx.config.linkcheck*`
- [x] images & data not committed to this repo (e.g. use https://github.com/premAI-io/static.premai.io instead)

### CODE REVIEW

**Review by casperdcl — COMMENTED** [review]
- probably need some brief summary for each model: what it is used for (e.g. `fake news generator`, `phishing email creator`, ...)
- are there any mitigation measures? (e.g. "train on your own data to avoid fake news" etc...)
- brief technical summary about how these LLMs work (is it just different training data from a malicious source?)

**Review by casperdcl — COMMENTED** [review]
made a bunch of changes; please do review :)

**Comment by uilfdj** [comment]
น

**Comment by uilfdj** [comment]
สวัสดี

**Review by uilfdj — APPROVED** [review]

**Review by aab83680-ship-it — APPROVED** [review]

**Pull request merged**
